spring:
  application:
    name: api-gateway
server:
  port: 2006
zuul:
  routes:
    api:
      path: /api/**
      serviceId: webstatistics-web
  add-host-header: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

