spring.application.name=config-server
server.port=2007
spring.cloud.config.server.git.uri=https://github.com/wujiazhen2/webstatistics-config.git
spring.cloud.config.server.git.search-paths=config-repo
spring.cloud.config.server.git.username=wujiazhen2
spring.cloud.config.server.git.password=wujiazhen22